const val = [{
  languages: {
    english: "en",
    spanish: "es",
    french: "fr",
    german: "de",
    italian: "it",
    portuguese: "pt",
    dutch: "nl",
    russian: "ru",
    japanese: "ja",
    chinese: "zh",
    arabic: "ar",
    hindi: "hi",
    bengali: "bn",
    korean: "ko",
    turkish: "tr",
    urdu: "ur",
    greek: "el",
    vietnamese: "vi",
    thai: "th",
    swahili: "sw",
    tamil: "ta",
    hebrew: "he",
    polish: "pl",
    hungarian: "hu",
    czech: "cs",
    slovak: "sk",
    romanian: "ro",
    bulgarian: "bg",
    ukrainian: "uk",
    norwegian: "no",
    swedish: "sv",
    danish: "da",
    finnish: "fi",
    icelandic: "is",
    malay: "ms",
    indonesian: "id",
    filipino: "fil",
    esperanto: "eo",
  },
}];

export default val;
